# Generated by Django 2.1.1 on 2018-10-12 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='qub_date',
            new_name='pub_date',
        ),
    ]
